### ISSUE TITLE
qtys at bottom of invoice

### ISSUE THREAD

**Issue by BLSTAFF** [erk91495/BL_Orders_2023#251]
qtys at bottom of invoice for 600 series tkys brst, rst, brst rst and total cases

**Comment by erk91495** [comment]
Not feasible to implement nor maintain need to pursue alternate ways to ID what is on a pallet

**Comment by erk91495** [comment]
Maybe add pick sheets that split pallet tickets by product series then we can use pallet tickets to ID what is on the pallet and how many pallets we should have.

**Comment by erk91495** [comment]
Could also be fixed by creating a category manager and having category reports listed out

**Comment by erk91495** [comment]
Went with Product Categories see Product Categories Milestone
