### ISSUE TITLE
Unpaid and Paid Invoice report per customer

### ISSUE THREAD

**Issue by BLSTAFF** [erk91495/BL_Orders_2023#276]
I'd like an invoice report for a given time period showing all invoices and "unpaid or paid" with the invoice total, payments and current balance for an individual customer of our choosing.  Currently, our unpaid invoice reports does not show all invoices regardless of payment status. Please include field for check number with associated payment.

**Comment by erk91495** [comment]
How do we want to handle multiple payments? (Table below each invoice, list of check/payment numbers inline)

**Comment by erk91495** [comment]
List out payments in table
