### ISSUE TITLE
3rd Party Shipping Invoice Date

### ISSUE THREAD

**Issue by BLSTAFF** [erk91495/BL_Orders_2023#302]
Submitter: Drew Bowman
When shipping via a 3rd party (ie. IDeal Meat), it would be nice to have the invoice date match the date the customer is going to actually receive the product.  Ex. If Ideals pick up date is a Thursday and the customer's delivery date is Monday, then the invoice date should generate as Monday.

**Comment by erk91495** [comment]
Could do this by setting pickup/delivery date to date items will be delivered and add a fill by date for the fill orders page
